Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.pyo", line 808, in __bootstrap_inner
  File "threading.pyo", line 761, in run
  File "ThreadManagers.pyo", line 294, in hashThread
IOError: [Errno 2] No such file or directory: 'D:\\DOCs\\PersonalProjects\\AppBin\\SyncingExp\\gitRepo\\dist\\data\\temp\\desk\\dir0.7z'

